version: '3'
services:

  redis:
    image: "redis:4.0.10"
    ports:
      - "6379:6379"

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DATABASE: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./db/seed.sql:/docker-entrypoint-initdb.d/seed.sql

  api:
    image: "node:10"
    user: "node"
    depends_on:
      - "db"
      - "redis"
    working_dir: /home/node/api
    volumes:
      - ./:/home/node/api
    links:
      - "db:database"
      - "redis:redis"
    env_file: ./.env
    environment:
      DB_HOST: database
    ports:
       - "${API_FRONT_PORT}:${API_FRONT_PORT}"
       - "${API_PORT}:${API_PORT}"
    depends_on:
      - db
    command: ./wait-for-it.sh -t 0 db:5432 -- ./wait-for-it.sh -t 0 redis:6379 -- npm run start
